[package]
name = "broken-app"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "baseline"
harness = false

[[bench]]
name = "criterion"  # Должен совпадать с именем файла в benches/
harness = false         #  Отключает libtest


# Разрешаем использование флагов санитайзеров
[unstable]
sanitizer = true

# Применяем санитайзер только к целевой платформе
# Но НЕ к proc-macro (они компилируются для хоста)
[target.'cfg(target_os = "linux")']
rustflags = ["-Zsanitizer=address"]