# Сеть
listen_addresses = 'localhost'
port = 8432
unix_socket_directories = '/tmp'

# Логи (удобно при ручном запуске)
logging_collector = on
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d.log'
log_statement = 'ddl'
log_min_messages = warning

# Ресурсы (для разработки/локального запуска)
max_connections = 20
shared_buffers = 128MB